
% This script was called by ephyFeatCmp_Fig2D.m


%% ==============================plot all parameters===================
figure;
markerSize = 20;
% ------------------ Tau.--------------------
s(1)=subplot(5,8,1);hold on;
nL23IT = size(ephsData_L23IT(:,1),1);
nITrorb = size(ephsData_ITrorb(:,1),1);
nL5IT = size(ephsData_L5IT(:,1),1);
nVEN = size(ephsData_VEN(:,1),1);
nL5ET = size(ephsData_L5ET(:,1),1);
nL6PC = size(ephsData_L6PC(:,1),1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(ephsData_L23IT(:,1),[nL23IT,1]);
Y(1:nITrorb,2) = reshape(ephsData_ITrorb(:,1),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(ephsData_L5IT(:,1),[nL5IT,1]);
Y(1:nVEN,4) = reshape(ephsData_VEN(:,1),[nVEN,1]);
Y(1:nL5ET,5) = reshape(ephsData_L5ET(:,1),[nL5ET,1]);
Y(1:nL6PC,6) = reshape(ephsData_L6PC(:,1),[nL6PC,1]);
scatter(ones(size(ephsData_L23IT,1),1),ephsData_L23IT(:,1),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(ephsData_ITrorb,1),1),ephsData_ITrorb(:,1),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(ephsData_L5IT,1),1),ephsData_L5IT(:,1),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(ephsData_VEN,1),1),ephsData_VEN(:,1),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(ephsData_L5ET,1),1),ephsData_L5ET(:,1),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(ephsData_L6PC,1),1),ephsData_L6PC(:,1),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,120],'xTick', [1,2,3,4,5,6], 'yTick',0:20:200,'box','off');
ylabel('Membrane time constant');
title(s(1),'Membrane time constant (ms)');
hold off;

% ------------------ Sag ratio --------------------
s(1)=subplot(5,8,2);hold on;
data_tem1 = ephsData_L23IT(:,2);data_tem1 = data_tem1(data_tem1>1); % exclude the unresonable.
data_tem2 = ephsData_ITrorb(:,2);data_tem2 = data_tem2(data_tem2>1);
data_tem3 = ephsData_L5IT(:,2);data_tem3 = data_tem3(data_tem3>1);
data_tem4 = ephsData_VEN(:,2);data_tem4 = data_tem4(data_tem4>1);
data_tem5 = ephsData_L5ET(:,2);data_tem5 = data_tem5(data_tem5>1);
data_tem6 = ephsData_L6PC(:,2);data_tem6 = data_tem6(data_tem6>1);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0.8,2],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:2,'box','off');
ylabel('Sag ratio');
title(s(1),'Sag ratio');
hold off;

% ------------------ Input resistance --------------------
s(3)=subplot(5,8,3);hold on;
data_tem1 = ephsData_L23IT(:,3);
data_tem2 = ephsData_ITrorb(:,3);
data_tem3 = ephsData_L5IT(:,3);
data_tem4 = ephsData_VEN(:,3);
data_tem5 = ephsData_L5ET(:,3);
data_tem6 = ephsData_L6PC(:,3);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,1000],'xTick', [1,2,3,4,5,6], 'yTick',0:250:1000,'box','off');
ylabel('Rm (MOhm)');
title(s(3),'Input resistance');
hold off;

% ------------------ Rest membrane potential --------------------
s(4)=subplot(5,8,4);
hold on;
data_tem1 = ephsData_L23IT(:,4);
data_tem2 = ephsData_ITrorb(:,4);
data_tem3 = ephsData_L5IT(:,4);
data_tem4 = ephsData_VEN(:,4);
data_tem5 = ephsData_L5ET(:,4);
data_tem6 = ephsData_L6PC(:,4);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-80,-20],'xTick', [1,2,3,4,5,6], 'yTick',-100:20:-20,'box','off');
ylabel('RMP (mV)');
title(s(4),'Rest membrane potential');
hold off;

% ------------------ Rheobase_pA --------------------
s(5)=subplot(5,8,5);
hold on;
data_tem1 = ephsData_L23IT(:,5);data_tem1 = data_tem1(data_tem1>0);
data_tem2 = ephsData_ITrorb(:,5);data_tem2 = data_tem2(data_tem2>0);
data_tem3 = ephsData_L5IT(:,5);data_tem3 = data_tem3(data_tem3>0);
data_tem4 = ephsData_VEN(:,5);data_tem4 = data_tem4(data_tem4>0);
data_tem5 = ephsData_L5ET(:,5);data_tem5 = data_tem5(data_tem5>0);
data_tem6 = ephsData_L6PC(:,5);data_tem6 = data_tem6(data_tem6>0);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,300],'xTick', [1,2,3,4,5,6], 'yTick',0:100:400,'box','off');
ylabel('Rheobase (pA)');
title(s(5),'Rheobase');
hold off;

% ------------------ Spike_Latency_ms --------------------
s(6)=subplot(5,8,6);
hold on;
data_tem1 = ephsData_L23IT(:,6);
data_tem2 = ephsData_ITrorb(:,6);
data_tem3 = ephsData_L5IT(:,6);
data_tem4 = ephsData_VEN(:,6);
data_tem5 = ephsData_L5ET(:,6);
data_tem6 = ephsData_L6PC(:,6);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,1000],'xTick', [1,2,3,4,5,6], 'yTick',0:250:1000,'box','off');
ylabel('Spike_Latency (ms)');
title(s(6),'Spike latency');
hold off;

% ------------------ Threshold --------------------
s(7)=subplot(5,8,7);
hold on;
data_tem1 = ephsData_L23IT(:,7);
data_tem2 = ephsData_ITrorb(:,7);
data_tem3 = ephsData_L5IT(:,7);
data_tem4 = ephsData_VEN(:,7);
data_tem5 = ephsData_L5ET(:,7);
data_tem6 = ephsData_L6PC(:,7);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1.2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-60,0],'xTick', [1,2,3,4,5,6], 'yTick',-60:10:-20,'box','off');
ylabel('Threshold (mV)');
title(s(7),'Threshold');
hold off;

% ------------------ AP_Amplitute --------------------
s(8)=subplot(5,8,8);
hold on;
data_tem1 = ephsData_L23IT(:,8); data_tem1 = data_tem1(data_tem1>60); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,8); data_tem2 = data_tem2(data_tem2>60);
data_tem3 = ephsData_L5IT(:,8); data_tem3 = data_tem3(data_tem3>60);
data_tem4 = ephsData_VEN(:,8); data_tem4 = data_tem4(data_tem4>60);
data_tem5 = ephsData_L5ET(:,8); data_tem5 = data_tem4(data_tem5>60);
data_tem6 = ephsData_L6PC(:,8); data_tem6 = data_tem5(data_tem6>60);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[50,150],'xTick', [1,2,3,4,5,6], 'yTick',0:30:120,'box','off');
ylabel('AP amplitute (mV)');
title(s(8),'AP_Amplitute');
hold off;

% ------------------ AHP_mV --------------------
s(9)=subplot(5,8,9);
hold on;
data_tem1 = ephsData_L23IT(:,9); data_tem1 = data_tem1(data_tem1<0); % exclude the unmeanable outliers.
data_tem2 = ephsData_ITrorb(:,9); data_tem2 = data_tem2(data_tem2<0);
data_tem3 = ephsData_L5IT(:,9); data_tem3 = data_tem3(data_tem3<0);
data_tem4 = ephsData_VEN(:,9);  data_tem4 = data_tem4(data_tem4<0);
data_tem5 = ephsData_L5ET(:,9); data_tem5 = data_tem5(data_tem5<0);
data_tem6 = ephsData_L6PC(:,9); data_tem6 = data_tem6(data_tem6<0);
nL23IT = size(data_tem1,1);  
nITrorb = size(data_tem2,1); 
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-30,10],'xTick', [1,2,3,4,5,6], 'yTick',-30:10:50,'box','off');
ylabel('AHP (mV)');
title(s(9),'AHP');
hold off;

% ------------------ Rise phase time --------------------
s(10)=subplot(5,8,10);
hold on;
data_tem1 = ephsData_L23IT(:,10); data_tem1 = data_tem1(data_tem1<2.5); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,10); data_tem2 = data_tem2(data_tem2<2.5);
data_tem3 = ephsData_L5IT(:,10); data_tem3 = data_tem3(data_tem3<2.5);
data_tem4 = ephsData_VEN(:,10); data_tem4 = data_tem4(data_tem4<2.5);
data_tem5 = ephsData_L5ET(:,10); data_tem5 = data_tem5(data_tem5<2.5);
data_tem6 = ephsData_L6PC(:,10); data_tem6 = data_tem6(data_tem6<2.5);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0.5,4],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:4,'box','off');
ylabel('Rise phase time (ms)');
title(s(10),'Rise phase time');
hold off;

% ------------------ Decay phase time --------------------
s(11)=subplot(5,8,11);
hold on;
data_tem1 = ephsData_L23IT(:,11); data_tem1 = data_tem1(data_tem1<15); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,11); data_tem2 = data_tem2(data_tem2<15);
data_tem3 = ephsData_L5IT(:,11); data_tem3 = data_tem3(data_tem3<15);
data_tem4 = ephsData_VEN(:,11); data_tem4 = data_tem4(data_tem4<15);
data_tem5 = ephsData_L5ET(:,11); data_tem5 = data_tem5(data_tem5<15);
data_tem6 = ephsData_L6PC(:,11); data_tem6 = data_tem6(data_tem6<15);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,25],'xTick', [1,2,3,4,5,6], 'yTick',0:5:30,'box','off');
ylabel('Decay phase time (ms)');
title(s(11),'Decay phase time');
hold off;

% ------------------ AP width --------------------
s(12)=subplot(5,8,12);
hold on;
data_tem1 = ephsData_L23IT(:,12); data_tem1 = data_tem1(data_tem1<5); data_tem1 = data_tem1(data_tem1>1); % exclude the unresonable.
data_tem2 = ephsData_ITrorb(:,12); data_tem2 = data_tem2(data_tem2<5); data_tem2 = data_tem2(data_tem2>1);
data_tem3 = ephsData_L5IT(:,12); data_tem3 = data_tem3(data_tem3<5); data_tem3 = data_tem3(data_tem3>1);
data_tem4 = ephsData_VEN(:,12); data_tem4 = data_tem4(data_tem4<5); data_tem4 = data_tem4(data_tem4>1);
data_tem5 = ephsData_L5ET(:,12); data_tem5 = data_tem5(data_tem5<5); data_tem5 = data_tem5(data_tem5>1);
data_tem6 = ephsData_L6PC(:,12); data_tem6 = data_tem6(data_tem6<5); data_tem6 = data_tem6(data_tem6>1);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,8],'xTick', [1,2,3,4,5,6], 'yTick',0:2:20,'box','off');
ylabel('AP width (ms)');
title(s(12),'AP width');
hold off;

% ------------------ Max_Spike_Number --------------------
s(13)=subplot(5,8,13);
hold on;
data_tem1 = ephsData_L23IT(:,13); %data_tem1 = data_tem1(data_tem1<5); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,13); %data_tem2 = data_tem2(data_tem2<5);
data_tem3 = ephsData_L5IT(:,13); %data_tem3 = data_tem3(data_tem3<5);
data_tem4 = ephsData_VEN(:,13); %data_tem4 = data_tem4(data_tem4<5);
data_tem5 = ephsData_L5ET(:,13); %data_tem5 = data_tem5(data_tem5<5);
data_tem6 = ephsData_L6PC(:,13); %data_tem6 = data_tem6(data_tem6<5);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,30],'xTick', [1,2,3,4,5,6], 'yTick',0:10:30,'box','off');
ylabel('Max number of spikes');
title(s(13),'Max number of spikes ');
hold off;

% ------------------ Max firing rate --------------------
s(14)=subplot(5,8,14);
hold on;
data_tem1 = ephsData_L23IT(:,14);
data_tem2 = ephsData_ITrorb(:,14);
data_tem3 = ephsData_L5IT(:,14);
data_tem4 = ephsData_VEN(:,14);
data_tem5 = ephsData_L5ET(:,14);
data_tem6 = ephsData_L6PC(:,14);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,60],'xTick', [1,2,3,4,5,6], 'yTick',0:10:100,'box','off');
ylabel('Max firing rate (spikes/s)');
title(s(14),'Max firing rate');
hold off;

% ------------------ Rebound_mV --------------------
s(15)=subplot(5,8,15);
hold on;
data_tem1 = ephsData_L23IT(:,15); data_tem1 = data_tem1(data_tem1>0);
data_tem2 = ephsData_ITrorb(:,15); data_tem2 = data_tem2(data_tem2>0);
data_tem3 = ephsData_L5IT(:,15); data_tem3 = data_tem3(data_tem3>0);
data_tem4 = ephsData_VEN(:,15); data_tem4 = data_tem4(data_tem4>0);
data_tem5 = ephsData_L5ET(:,15); data_tem5 = data_tem5(data_tem5>0);
data_tem6 = ephsData_L6PC(:,15); data_tem6 = data_tem6(data_tem6>0);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-10,40],'xTick', [1,2,3,4,5,6], 'yTick',0:10:50,'box','off');
ylabel('Rebound (mV)');
title(s(15),'Rebound');
hold off;

% ------------------number of rebound spikes --------------------
s(16)=subplot(5,8,16);
hold on;
data_tem1 = ephsData_L23IT(:,16);
data_tem2 = ephsData_ITrorb(:,16);
data_tem3 = ephsData_L5IT(:,16);
data_tem4 = ephsData_VEN(:,16);
data_tem5 = ephsData_L5ET(:,16);
data_tem6 = ephsData_L6PC(:,16);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,6],'xTick', [1,2,3,4,5,6], 'yTick',0:2:50,'box','off');
ylabel('# of rebound Spikes');
title(s(16),'Rebound Spikes');
hold off;

% ------------------aveAPwidth_maxSweep--------------------
s(17)=subplot(5,8,17);
hold on;
data_tem1 = ephsData_L23IT(:,17); data_tem1 = data_tem1(data_tem1<9.5); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,17); data_tem2 = data_tem2(data_tem2<9.5);
data_tem3 = ephsData_L5IT(:,17); data_tem3 = data_tem3(data_tem3<9.5);
data_tem4 = ephsData_VEN(:,17); data_tem4 = data_tem4(data_tem4<9.5);
data_tem5 = ephsData_L5ET(:,17); data_tem5 = data_tem5(data_tem5<9.5);
data_tem6 = ephsData_L6PC(:,17); data_tem6 = data_tem6(data_tem6<9.5);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,15],'xTick', [1,2,3,4,5,6], 'yTick',0:3:15,'box','off');
ylabel('Ave AP width (ms)');
title(s(17),'ave AP width');
hold off;

% ------------------RisDecayTRatio--------------------
s(18)=subplot(5,8,18);
hold on;
data_tem1 = ephsData_L23IT(:,18);
data_tem2 = ephsData_ITrorb(:,18);
data_tem3 = ephsData_L5IT(:,18);
data_tem4 = ephsData_VEN(:,18);
data_tem5 = ephsData_L5ET(:,18);
data_tem6 = ephsData_L6PC(:,18);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,1.0],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:2,'box','off');
ylabel('AP rise-decay ratio');
title(s(18),'AP rise-decay ratio');
hold off;

% ------------------AHP_latency--------------------
s(19)=subplot(5,8,19);
hold on;
data_tem1 = ephsData_L23IT(:,19);
data_tem2 = ephsData_ITrorb(:,19);
data_tem3 = ephsData_L5IT(:,19);
data_tem4 = ephsData_VEN(:,19);
data_tem5 = ephsData_L5ET(:,19);
data_tem6 = ephsData_L6PC(:,19);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1.0,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,150],'xTick', [1,2,3,4,5,6], 'yTick',0:25:200,'box','off');
ylabel('AHP latency (ms)');
title(s(19),'AHP latency');
hold off;

% ------------------AP width ratio--------------------
s(20)=subplot(5,8,20);
hold on;
data_tem1 = ephsData_L23IT(:,20);
data_tem2 = ephsData_ITrorb(:,20);
data_tem3 = ephsData_L5IT(:,20);
data_tem4 = ephsData_VEN(:,20);
data_tem5 = ephsData_L5ET(:,20);
data_tem6 = ephsData_L6PC(:,20);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,2],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:3,'box','off');
ylabel('AP width ratio');
title(s(20),'AP width ratio');
hold off;

% ------------------AP Amplitude ratio--------------------
s(21)=subplot(5,8,21);
hold on;
data_tem1 = ephsData_L23IT(:,21); data_tem1 = data_tem1(data_tem1<3); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,21); data_tem2 = data_tem2(data_tem2<3);
data_tem3 = ephsData_L5IT(:,21); data_tem3 = data_tem3(data_tem3<3);
data_tem4 = ephsData_VEN(:,21); data_tem4 = data_tem4(data_tem4<3);
data_tem5 = ephsData_L5ET(:,21); data_tem5 = data_tem5(data_tem5<3);
data_tem6 = ephsData_L6PC(:,21); data_tem6 = data_tem6(data_tem6<3);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0.5,4],'xTick', [1,2,3,4,5,6], 'yTick',0:1:5,'box','off');
ylabel('AP amp ratio');
title(s(21),'AP amp ratio');
hold off;

% ------------------ampAdaptIdx--------------------
s(22)=subplot(5,8,22);
hold on;
data_tem1 = ephsData_L23IT(:,22); data_tem1 = data_tem1(data_tem1>0.03); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,22); data_tem2 = data_tem2(data_tem2>0.03);
data_tem3 = ephsData_L5IT(:,22); data_tem3 = data_tem3(data_tem3>0.03);
data_tem4 = ephsData_VEN(:,22); data_tem4 = data_tem4(data_tem4>0.03);
data_tem5 = ephsData_L5ET(:,22); data_tem5 = data_tem5(data_tem5>0.03);
data_tem6 = ephsData_L6PC(:,22); data_tem6 = data_tem6(data_tem6>0.03);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,1.5],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:3,'box','off');
ylabel('Amp adapt index');
title(s(22),'Amp adapt index');
hold off;

% ------------------amp_FanoFactor--------------------
s(23)=subplot(5,8,23);
hold on;
data_tem1 = log( ephsData_L23IT(:,23) ); %data_tem1 = data_tem1(data_tem1<30); % exclude the outliers.
data_tem2 = log( ephsData_ITrorb(:,23) ); %data_tem2 = data_tem2(data_tem2<30);
data_tem3 = log( ephsData_L5IT(:,23) ); %data_tem2 = data_tem2(data_tem2<30);
data_tem4 = log( ephsData_VEN(:,23) ); %data_tem3 = data_tem3(data_tem3<30);
data_tem5 = log( ephsData_L5ET(:,23) ); %data_tem4 = data_tem4(data_tem4<30);
data_tem6 = log( ephsData_L6PC(:,23) ); %data_tem5 = data_tem5(data_tem5<30);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-2,8],'xTick', [1,2,3,4,5,6], 'yTick',-2:2:12,'box','off');
ylabel('Amp Fano Factor');
title(s(23),'Amp Fano Factor');
hold off;

% ------------------amp_CV--------------------
s(24)=subplot(5,8,24);
hold on;
data_tem1 = ephsData_L23IT(:,24); data_tem1 = data_tem1(data_tem1<2);
data_tem2 = ephsData_ITrorb(:,24);data_tem2 = data_tem2(data_tem2<2);
data_tem3 = ephsData_L5IT(:,24);data_tem3 = data_tem3(data_tem3<2);
data_tem4 = ephsData_VEN(:,24);data_tem4 = data_tem4(data_tem4<2);
data_tem5 = ephsData_L5ET(:,24);data_tem5 = data_tem5(data_tem5<2);
data_tem6 = ephsData_L6PC(:,24);data_tem6 = data_tem6(data_tem6<2);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,3],'xTick', [1,2,3,4,5,6], 'yTick',0:1:3,'box','off');
ylabel('Amp CV');
title(s(24),'Amp CV');
hold off;

% ------------------ISI_FanoFactor--------------------
s(25)=subplot(5,8,25);
hold on;
data_tem1 = ephsData_L23IT(:,25); data_tem1 = data_tem1(data_tem1<25); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,25); data_tem2 = data_tem2(data_tem2<25);
data_tem3 = ephsData_L5IT(:,25); data_tem3 = data_tem3(data_tem3<25);
data_tem4 = ephsData_VEN(:,25); data_tem4 = data_tem4(data_tem4<25);
data_tem5 = ephsData_L5ET(:,25); data_tem5 = data_tem5(data_tem5<25);
data_tem6 = ephsData_L6PC(:,25); data_tem6 = data_tem6(data_tem6<25);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-10,30],'xTick', [1,2,3,4,5,6], 'yTick',-10:2:0,'box','off');
ylabel('ISI_Fano Factor');
title(s(25),'ISI Fano Factor');
hold off;

% ------------------ISI adatptation index--------------------
s(26)=subplot(5,8,26);
hold on;
data_tem1 = ephsData_L23IT(:,26);
data_tem2 = ephsData_ITrorb(:,26);
data_tem3 = ephsData_L5IT(:,26);
data_tem4 = ephsData_VEN(:,26);
data_tem5 = ephsData_L5ET(:,26);
data_tem6 = ephsData_L6PC(:,26);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-50,50],'xTick', [1,2,3,4,5,6], 'yTick',-100:50:100,'box','off');
ylabel('ISI adatptation index');
title(s(26),'ISI adatptation index');
hold off;

% ------------------ISI ratio --------------------
s(27)=subplot(5,8,27);
hold on;
data_tem1 = ephsData_L23IT(:,27);
data_tem2 = ephsData_ITrorb(:,27);
data_tem3 = ephsData_L5IT(:,27);
data_tem4 = ephsData_VEN(:,27);
data_tem5 = ephsData_L5ET(:,27);
data_tem6 = ephsData_L6PC(:,27);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-100,100],'xTick', [1,2,3,4,5,6], 'yTick',-500:250:500,'box','off');
ylabel('ISI ratio');
title(s(27),'ISI ratio');
hold off;

% ------------------ISI CV --------------------
s(28)=subplot(5,8,28);
hold on;
data_tem1 = ephsData_L23IT(:,28); data_tem1 = data_tem1(data_tem1>-15); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,28); data_tem2 = data_tem2(data_tem2>-15);
data_tem3 = ephsData_L5IT(:,28); data_tem3 = data_tem3(data_tem3>-15);
data_tem4 = ephsData_VEN(:,28); data_tem4 = data_tem4(data_tem4>-15);
data_tem5 = ephsData_L5ET(:,28); data_tem5 = data_tem5(data_tem5>-15);
data_tem6 = ephsData_L6PC(:,28); data_tem6 = data_tem6(data_tem6>-15);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-15,10],'xTick', [1,2,3,4,5,6], 'yTick',-20:5:20,'box','off');
ylabel('ISI CV');
title(s(28),'ISI CV');
hold off;

% ------------------ISI phaseT ratio --------------------
s(29)=subplot(5,8,29);
hold on;
data_tem1 = ephsData_L23IT(:,29);
data_tem2 = ephsData_ITrorb(:,29);
data_tem3 = ephsData_L5IT(:,29);
data_tem4 = ephsData_VEN(:,29);
data_tem5 = ephsData_L5ET(:,29);
data_tem6 = ephsData_L6PC(:,29);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-0.1,2],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:2,'box','off');
ylabel('ISI phaseT ratio');
title(s(29),'ISI phaseT ratio');
hold off;

% ------------------ISI phaseT ratio CV--------------------
s(30)=subplot(5,8,30);
hold on;
data_tem1 = ephsData_L23IT(:,30);
data_tem2 = ephsData_ITrorb(:,30);
data_tem3 = ephsData_L5IT(:,30);
data_tem4 = ephsData_VEN(:,30);
data_tem5 = ephsData_L5ET(:,30);
data_tem6 = ephsData_L6PC(:,30);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-0.1,1.5],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:2,'box','off');
ylabel('ISI phaseT ratio CV');
title(s(30),'ISI phaseT ratio CV');
hold off;

% ------------------latency_slope--------------------
s(31)=subplot(5,8,31);
hold on;
data_tem1 = ephsData_L23IT(:,31);
data_tem2 = ephsData_ITrorb(:,31);
data_tem3 = ephsData_L5IT(:,31);
data_tem4 = ephsData_VEN(:,31);
data_tem5 = ephsData_L5ET(:,31);
data_tem6 = ephsData_L6PC(:,31);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-0.1,2],'xTick', [1,2,3,4,5,6], 'yTick',0:0.5:2,'box','off');
ylabel('Latency slope');
title(s(31),'latency slope');
hold off;

% ------------------Firing rate slope--------------------
s(32)=subplot(5,8,32);
hold on;
data_tem1 = ephsData_L23IT(:,32);
data_tem2 = ephsData_ITrorb(:,32);
data_tem3 = ephsData_L5IT(:,32);
data_tem4 = ephsData_VEN(:,32);
data_tem5 = ephsData_L5ET(:,32);
data_tem6 = ephsData_L6PC(:,32);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-0.05,0.3],'xTick', [1,2,3,4,5,6], 'yTick',0:0.1:0.3,'box','off');
ylabel('Firing rate slope');
title(s(32),'Firing rate slope');
hold off;

% ------------------First ISI slope--------------------
s(33)=subplot(5,8,33);
hold on;
data_tem1 = ephsData_L23IT(:,33);
data_tem2 = ephsData_ITrorb(:,33);
data_tem3 = ephsData_L5IT(:,33);
data_tem4 = ephsData_VEN(:,33);
data_tem5 = ephsData_L5ET(:,33);
data_tem6 = ephsData_L6PC(:,33);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-2,2],'xTick', [1,2,3,4,5,6], 'yTick',-3:1:5,'box','off');
ylabel('First ISI slope');
title(s(33),'First ISI slope');
hold off;

% ------------------ISI adpIdx slope--------------------
s(34)=subplot(5,8,34);
hold on;
data_tem1 = ephsData_L23IT(:,34);
data_tem2 = ephsData_ITrorb(:,34);
data_tem3 = ephsData_L5IT(:,34);
data_tem4 = ephsData_VEN(:,34);
data_tem5 = ephsData_L5ET(:,34);
data_tem6 = ephsData_L6PC(:,34);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-20,40],'xTick', [1,2,3,4,5,6], 'yTick',-20:20:40,'box','off');
ylabel('SI adpIdx slope');
title(s(34),'ISI adpIdx slope');
hold off;

% ------------------Amp AdpIdx slope--------------------
s(35)=subplot(5,8,35);
hold on;
data_tem1 = ephsData_L23IT(:,35);
data_tem2 = ephsData_ITrorb(:,35);
data_tem3 = ephsData_L5IT(:,35);
data_tem4 = ephsData_VEN(:,35);
data_tem5 = ephsData_L5ET(:,35);
data_tem6 = ephsData_L6PC(:,35);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[-5,5],'xTick', [1,2,3,4,5,6], 'yTick',-5:2.5:5,'box','off');
ylabel('Amp AdpIdx slope');
title(s(35),'Amp AdpIdx slope');
hold off;

% ------------------first Spike Phase Area--------------------
s(36)=subplot(5,8,36);
hold on;
data_tem1 = ephsData_L23IT(:,36);
data_tem2 = ephsData_ITrorb(:,36);
data_tem3 = ephsData_L5IT(:,36);
data_tem4 = ephsData_VEN(:,36);
data_tem5 = ephsData_L5ET(:,36);
data_tem6 = ephsData_L6PC(:,36);
% data_tem1 = log( ephsData_L23IT(:,36) );
% data_tem2 = log( ephsData_ITrorb(:,36) );
% data_tem3 = log( ephsData_L5IT(:,36) );
% data_tem4 = log( ephsData_VEN(:,36) );
% data_tem5 = log( ephsData_L5ET(:,36) );
% data_tem6 = log( ephsData_L6PC(:,36) );
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
% set(gca,'xlim',[0,7],'ylim',[0,25000],'xTick', [1,2,3,4,5,6], 'yTick',-0:5000:25000,'box','off');
% set(gca,'xlim',[0,7],'ylim',[6,12],'xTick', [1,2,3,4,5,6], 'yTick',6:2:16,'box','off');
set(gca,'yscale','log','xlim',[0,7],'ylim',[100,1000000],'box','off');
ylabel('First Spike Phase Area (mV*mV/s)');
title(s(36),'First Spike Phase Area');
hold off;

% ------------------first Spike Phase Perimeter--------------------
s(37)=subplot(5,8,37);
hold on;
data_tem1 = ephsData_L23IT(:,37);
data_tem2 = ephsData_ITrorb(:,37);
data_tem3 = ephsData_L5IT(:,37);
data_tem4 = ephsData_VEN(:,37);
data_tem5 = ephsData_L5ET(:,37);
data_tem6 = ephsData_L6PC(:,37);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,1000],'xTick', [1,2,3,4,5,6], 'yTick',-0:250:1000,'box','off');
ylabel('First spike phase perimeter');
title(s(37),'First spike phase perimeter');
hold off;

% ------------------first Spike Phase Area ratio--------------------
s(38)=subplot(5,8,38);
hold on;
data_tem1 = ephsData_L23IT(:,38);
data_tem2 = ephsData_ITrorb(:,38);
data_tem3 = ephsData_L5IT(:,38);
data_tem4 = ephsData_VEN(:,38);
data_tem5 = ephsData_L5ET(:,38);
data_tem6 = ephsData_L6PC(:,38);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,30],'xTick', [1,2,3,4,5,6], 'yTick',-0:10:30,'box','off');
ylabel('First spike phase area ratio');
title(s(38),'First spike phase area ratio');
hold off;

% ------------------first Spike Phase Perimeter ratio--------------------
s(39)=subplot(5,8,39);hold on;
data_tem1 = ephsData_L23IT(:,39); data_tem1 = data_tem1(data_tem1<4.5); % exclude the outliers.
data_tem2 = ephsData_ITrorb(:,39); data_tem2 = data_tem2(data_tem2<4.5);
data_tem3 = ephsData_L5IT(:,39); data_tem3 = data_tem3(data_tem3<4.5);
data_tem4 = ephsData_VEN(:,39);  data_tem4 = data_tem4(data_tem4<4.5);
data_tem5 = ephsData_L5ET(:,39); data_tem5 = data_tem5(data_tem5<4.5);
data_tem6 = ephsData_L6PC(:,39); data_tem6 = data_tem6(data_tem6<4.5);
nL23IT = size(data_tem1,1);
nITrorb = size(data_tem2,1);
nL5IT = size(data_tem3,1);
nVEN = size(data_tem4,1);
nL5ET = size(data_tem5,1);
nL6PC = size(data_tem6,1);
nMax = max([nL23IT,nITrorb,nL5IT,nVEN,nL5ET,nL6PC]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(data_tem1,[nL23IT,1]);
Y(1:nITrorb,2) = reshape(data_tem2,[nITrorb,1]);
Y(1:nL5IT,3) = reshape(data_tem3,[nL5IT,1]);
Y(1:nVEN,4) = reshape(data_tem4,[nVEN,1]);
Y(1:nL5ET,5) = reshape(data_tem5,[nL5ET,1]);
Y(1:nL6PC,6) = reshape(data_tem6,[nL6PC,1]);
scatter(ones(length(data_tem1),1),data_tem1,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(length(data_tem2),1),data_tem2,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(length(data_tem3),1),data_tem3,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(length(data_tem4),1),data_tem4,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(length(data_tem5),1),data_tem5,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(length(data_tem6),1),data_tem6,markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',2,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,7],'ylim',[0,5],'xTick', [1,2,3,4,5,6], 'yTick',-0:2.5:5,'box','off');
ylabel('First spike phase perimeter ratio');
title(s(39),'First spike phase perimeter ratio');
hold off;