% this script is called by plot3H_morphFeatCmp.m, and plot the supplmentary figure 10.

nPara = length(morphParaNames);
figure;
markerSize = 30;
n=0;

col_idx = 1;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',0.5,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(s(n),'xlim',[0,6.9],'ylim',[200,60000],'xTick', 1:10, 'box','off','YScale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;
    
col_idx = 8;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',0.5,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(s(n),'xlim',[0,6.9],'ylim',[0,3500],'xTick', 1:10, 'box','off');%,'YScale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 12;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',0.5,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,3500],'xTick', 1:10, 'box','off');%,'YScale','log');
ylabel('Apical dendrite height (um)');
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 13;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,10],'xTick', 1:10, 'box','off');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 14;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,10000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 16;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,30],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 18;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,15],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 19;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,10000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 21;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,5000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 22;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[-700,300],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 23;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[-5,100],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 25;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,80],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 26;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[-1,20],'xTick', 1:10, 'yTick', 0:5:20, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 27;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,20],'xTick', 1:10, 'yTick', 0:5:20, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 3;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[-5,120],'xTick', 1:10, 'yTick', 0:50:100, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 32;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[-10,80],'xTick', 1:10, 'yTick', 0:20:100, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 33;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,1],'xTick', 1:10, 'yTick', 0:0.2:1, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 35;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,1],'xTick', 1:10, 'yTick', 0:0.2:1, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 36;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[500,100000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 38;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[-0.1,1.6],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 39;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0.1,1.1],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 40;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,4.5],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 42;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[5,25],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 43;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[1000,500000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 44;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[0,6],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 45;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[-0.1,1.1],'xTick', 1:10, 'box','off');%,'yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 48;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[1000,500000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 53;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[500,500000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 53;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[500,500000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;

col_idx = 57;
n = n+1;
s(n)=subplot(5,6,n);
hold on;
nL23IT = size(morphData_L23IT(:,col_idx),1);
nITrorb = size(morphData_ITrorb(:,col_idx),1);
nL5IT = size(morphData_L5IT(:,col_idx),1);
nVEN = size(morphData_VEN(:,col_idx),1);
nL5ET = size(morphData_L5ET(:,col_idx),1);
nL6PC = size(morphData_L6PC(:,col_idx),1);
nMax = max([nL23IT,nL5IT,nVEN,nL6PC,nL5ET]);
Y = nan(nMax,6);
Y(1:nL23IT,1) = reshape(morphData_L23IT(:,col_idx),[nL23IT,1]) ;
Y(1:nITrorb,2) = reshape(morphData_ITrorb(:,col_idx),[nITrorb,1]);
Y(1:nL5IT,3) = reshape(morphData_L5IT(:,col_idx),[nL5IT,1]);
Y(1:nVEN,4) = reshape(morphData_VEN(:,col_idx),[nVEN,1]) ;
Y(1:nL5ET,5) = reshape(morphData_L5ET(:,col_idx),[nL5ET,1]) ;
Y(1:nL6PC,6) = reshape(morphData_L6PC(:,col_idx),[nL6PC,1]) ;
scatter(ones(size(morphData_L23IT,1),1),morphData_L23IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{1});
scatter(2*ones(size(morphData_ITrorb,1),1),morphData_ITrorb(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{2});
scatter(3*ones(size(morphData_L5IT,1),1),morphData_L5IT(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{3});
scatter(4*ones(size(morphData_VEN,1),1),morphData_VEN(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{4});
scatter(5*ones(size(morphData_L5ET,1),1),morphData_L5ET(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{5});
scatter(6*ones(size(morphData_L6PC,1),1),morphData_L6PC(:,col_idx),markerSize,'marker','.','jitter','on','jitterAmount',0.1,'markerEdgeColor',colorTable{6});
h=boxplot(Y,'Notch','off','Labels',{'L23IT','IT_RORB','L5IT','VEN','L5ET','L6PC'},'whisker',1,'symbol','','colors','k');
set(h,{'linew'},{0.5});
set(gca,'xlim',[0,6.9],'ylim',[500,500000],'xTick', 1:10, 'box','off','yscale','log');
ylabel(morphParaNames{col_idx});
title(s(n),morphParaNames{col_idx});
hold off;


